development:
  adapter: postgresql
  encoding: utf-8
  database: kmlaalumni_development
  pool: 5
  port: 5432
  username: minjok
  password:	kmla1996

test:
  adapter: postgresql
  encoding: utf-8
  database: kmlaalumni_test
  pool: 5
  port: 5432
  username: minjok
  password: kmla1996

production:
  adapter: postgresql
  encoding: utf-8
  database: kmlaalumni_production
  pool: 5
  username: minjok
  password: kmla1996
